import type { UIContext } from '../context';
import type { UserThemeEditSession } from '../../arona-clicker/services/user-theme-service';
import type { UserThemeToken } from '../../arona-clicker/types/user-theme';
import type { ComponentPlacementDef, PresentationLayerDef, PresentationRegion } from '../../engine/types/theme';

const TOKENS: readonly UserThemeToken[] = ['primary', 'primaryStrong', 'bg', 'bgAlt', 'panel', 'panelAlt', 'text', 'muted', 'accent', 'danger'];
const TOKEN_LABELS: Record<UserThemeToken, string> = { primary: '主色', primaryStrong: '强调主色', bg: '背景', bgAlt: '背景辅助', panel: '面板', panelAlt: '面板辅助', text: '正文', muted: '弱文本', accent: '点缀', danger: '警告' };
const REGIONS: readonly PresentationRegion[] = ['shell', 'header', 'leftPanel', 'centerPanel', 'rightPanel', 'footer', 'story', 'modal'];
const REGION_LABELS: Record<PresentationRegion, string> = { shell: '整体', header: '顶部栏', leftPanel: '左侧栏', centerPanel: '中部信息栏', rightPanel: '右侧栏', footer: '底部栏', story: '剧情区', modal: '弹窗' };
const ANCHORS = ['top-left', 'top-right', 'bottom-left', 'bottom-right', 'center'] as const;

export function renderUserThemeEditor(ctx: UIContext, session: UserThemeEditSession, active: boolean, sources: readonly string[]): string {
  const draft = session.draft;
  const presentation = draft.presentation ?? { layers: [], components: [] };
  const components = presentation.components ?? [];
  return `<div class="user-theme-editor ${active ? '' : 'is-readonly'}" data-user-theme-session="${ctx.escapeHtml(session.id)}">
    <div class="user-theme-editor-status ${active ? 'is-active' : 'is-locked'}"><span class="status-dot"></span><span>${active ? '编辑服务已开放 · 实时预览中' : '编辑器只读'}</span><small>${active ? `能力来源 ${sources.length} 个` : '需要 Active Affector 提供 user-theme.editor'}</small></div>
    <div class="user-theme-workspace">
      <aside class="user-theme-nav"><button class="user-theme-nav-item is-active" type="button" data-theme-editor-section="colors">颜色 Token</button><button class="user-theme-nav-item" type="button" data-theme-editor-section="layers">区域图层 (${presentation.layers?.length ?? 0})</button><button class="user-theme-nav-item" type="button" data-theme-editor-section="components">组件 (${components.length})</button></aside>
      <aside class="user-theme-inspector"><section data-theme-editor-panel="colors"><div class="user-theme-section-head"><strong>颜色系统</strong><small>清空后跟随上一层</small></div><div class="user-theme-token-grid">${TOKENS.map(token => `<label class="user-theme-token"><span>${TOKEN_LABELS[token]}</span><input type="color" data-user-theme-token="${token}" value="${colorValue(draft.tokens?.[token])}" ${active ? '' : 'disabled'}><button type="button" class="user-theme-token-clear" data-user-theme-token-clear="${token}" ${active ? '' : 'disabled'}>清空</button><code>${ctx.escapeHtml(draft.tokens?.[token] ?? '跟随上一层')}</code></label>`).join('')}</div></section><section data-theme-editor-panel="layers" hidden><div class="user-theme-section-head"><strong>区域图层</strong><small>图层值只能使用已注册资源或安全颜色</small></div>${renderLayers(ctx, presentation.layers ?? [], active)}</section><section data-theme-editor-panel="components" hidden><div class="user-theme-section-head"><strong>组件位置</strong><small>相对父区域定位</small></div>${renderComponents(ctx, components, active)}</section></aside>
    </div><label class="user-theme-enabled"><input type="checkbox" data-user-theme-enabled ${ctx.game.state.userTheme?.enabled !== false ? 'checked' : ''} ${active ? '' : 'disabled'}> 保存后应用自定主题</label><div class="user-theme-editor-error" data-user-theme-error hidden></div>
  </div>`;
}

function renderLayers(ctx: UIContext, layers: readonly PresentationLayerDef[], active: boolean): string { if (!layers.length) return '<p class="modal-empty">暂无自定义图层。可通过受控主题数据添加图层。</p>'; return layers.map((layer, index) => `<label class="user-theme-field"><span>${ctx.escapeHtml(layer.id ?? `图层 ${index + 1}`)} · 区域</span><select data-user-theme-layer-region="${index}" ${active ? '' : 'disabled'}>${REGIONS.map(region => `<option value="${region}" ${layer.region === region ? 'selected' : ''}>${REGION_LABELS[region]}</option>`).join('')}</select><small>${layer.kind} · ${ctx.escapeHtml(layer.value)}</small></label>`).join(''); }
function renderComponents(ctx: UIContext, components: readonly ComponentPlacementDef[], active: boolean): string { if (!components.length) return '<p class="modal-empty">暂无自定义组件。当前版本先支持已声明组件的安全定位编辑。</p>'; return components.map(component => `<fieldset class="user-theme-component"><legend>${ctx.escapeHtml(component.id)}</legend><label class="user-theme-field"><span>父级</span><select data-user-theme-component-parent="${ctx.escapeHtml(component.id)}" ${active ? '' : 'disabled'}>${REGIONS.map(region => `<option value="${region}" ${component.parent === region ? 'selected' : ''}>${REGION_LABELS[region]}</option>`).join('')}${components.filter(parent => parent.id !== component.id).map(parent => `<option value="${ctx.escapeHtml(parent.id)}" ${component.parent === parent.id ? 'selected' : ''}>组件 · ${ctx.escapeHtml(parent.id)}</option>`).join('')}</select></label><div class="user-theme-anchor-grid" aria-label="${ctx.escapeHtml(component.id)} 锚点">${ANCHORS.map(anchor => `<button type="button" class="${component.anchor === anchor ? 'active' : ''}" title="${anchor}" data-user-theme-component-anchor="${ctx.escapeHtml(component.id)}" data-anchor="${anchor}" ${active ? '' : 'disabled'}>${anchor === 'top-left' ? '↖' : anchor === 'top-right' ? '↗' : anchor === 'bottom-left' ? '↙' : anchor === 'bottom-right' ? '↘' : '·'}</button>`).join('')}</div><div class="user-theme-number-row"><label>X <input type="number" data-user-theme-component-x="${ctx.escapeHtml(component.id)}" value="${component.offset?.x ?? 0}" ${active ? '' : 'disabled'}></label><label>Y <input type="number" data-user-theme-component-y="${ctx.escapeHtml(component.id)}" value="${component.offset?.y ?? 0}" ${active ? '' : 'disabled'}></label></div><small>位置相对于父级，单位：${component.offset?.unit ?? 'percent'}</small></fieldset>`).join(''); }
function colorValue(value: string | undefined): string { return /^#[0-9a-f]{6}$/i.test(value ?? '') ? value! : '#6b8cff'; }
